-- Apply this migration to GAME_DATABASE_URL (the arena/game database), never
-- to PORTAL_DATABASE_URL.
--
-- This is the non-destructive foundation for one authoritative group and
-- membership model shared by every game server. Existing Admins.Core,
-- VIPCore, and portal identity tables are intentionally left untouched. A
-- later, audited cutover migration can copy their data into these tables and
-- switch readers only after the two representations have been compared.
--
-- UUID values are generated by the application/migration tooling and stored
-- lowercase. Avoid database-generated UUID defaults so this DDL behaves the
-- same on MariaDB 10.5 and MySQL 8.

CREATE TABLE IF NOT EXISTS arena_scopes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  scope_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope_key VARCHAR(96) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  scope_type ENUM('global', 'server') NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  admin_server_guid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  vip_server_id BIGINT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY arena_scopes_uuid_unique (scope_uuid),
  UNIQUE KEY arena_scopes_key_unique (scope_key),
  UNIQUE KEY arena_scopes_admin_guid_unique (admin_server_guid),
  UNIQUE KEY arena_scopes_vip_server_unique (vip_server_id),
  KEY arena_scopes_browse (enabled, scope_type, display_name, id),
  CONSTRAINT arena_scopes_uuid_valid CHECK (
    scope_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_scopes_key_valid CHECK (
    scope_key REGEXP '^[a-z0-9][a-z0-9._:-]{0,95}$'
  ),
  CONSTRAINT arena_scopes_admin_guid_valid CHECK (
    admin_server_guid IS NULL OR
    admin_server_guid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_scopes_vip_server_valid CHECK (
    vip_server_id IS NULL OR vip_server_id >= 0
  ),
  CONSTRAINT arena_scopes_locator_shape CHECK (
    (
      scope_type = 'global' AND
      admin_server_guid IS NULL AND
      (vip_server_id IS NULL OR vip_server_id = 0)
    ) OR
    (
      scope_type = 'server' AND
      (admin_server_guid IS NOT NULL OR vip_server_id IS NOT NULL) AND
      (vip_server_id IS NULL OR vip_server_id > 0)
    )
  ),
  CONSTRAINT arena_scopes_version_positive CHECK (row_version >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Scope zero is the network-wide target for portal-bought VIP. Native VIP
-- sid=0 rows can be imported here, while sid=1 and Admins.Core GUIDs receive
-- explicit server scopes during the later data migration.
INSERT IGNORE INTO arena_scopes
  (
    scope_uuid,
    scope_key,
    scope_type,
    display_name,
    admin_server_guid,
    vip_server_id,
    enabled,
    row_version
  )
VALUES
  (
    '00000000-0000-0000-0000-000000000001',
    'global',
    'global',
    'All ARENA servers',
    NULL,
    0,
    TRUE,
    1
  );

CREATE TABLE IF NOT EXISTS arena_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  legacy_portal_group_id BIGINT UNSIGNED NULL,
  group_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  group_type ENUM('admin', 'vip', 'custom') NOT NULL,
  external_key VARCHAR(100) NULL,
  vip_family_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  display_name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  badge_label VARCHAR(32) NOT NULL,
  badge_icon_key VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci
    NOT NULL DEFAULT 'shield',
  badge_color CHAR(7) CHARACTER SET ascii COLLATE ascii_general_ci
    NOT NULL DEFAULT '#f0b35a',
  badge_soft_color CHAR(7) CHARACTER SET ascii COLLATE ascii_general_ci
    NOT NULL DEFAULT '#ffe4b8',
  profile_priority SMALLINT NOT NULL DEFAULT 0,
  rank_weight INT NOT NULL DEFAULT 0,
  immunity INT UNSIGNED NOT NULL DEFAULT 0,
  definition JSON NOT NULL,
  baseline_permissions JSON NOT NULL,
  capability_keys JSON NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_actor VARCHAR(64) NOT NULL,
  updated_by_actor VARCHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY arena_groups_uuid_unique (group_uuid),
  UNIQUE KEY arena_groups_legacy_portal_unique (legacy_portal_group_id),
  UNIQUE KEY arena_groups_key_unique (group_key),
  UNIQUE KEY arena_groups_external_unique (group_type, external_key),
  UNIQUE KEY arena_groups_vip_subscription_ref
    (id, group_type, vip_family_key),
  KEY arena_groups_browse
    (enabled, group_type, profile_priority, display_name, id),
  KEY arena_groups_vip_family
    (group_type, vip_family_key, enabled, rank_weight, id),
  CONSTRAINT arena_groups_uuid_valid CHECK (
    group_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_groups_key_valid CHECK (
    group_key REGEXP '^[a-z0-9][a-z0-9._:-]{0,63}$'
  ),
  CONSTRAINT arena_groups_source_shape CHECK (
    (group_type = 'custom' AND external_key IS NULL) OR
    (group_type IN ('admin', 'vip') AND external_key IS NOT NULL)
  ),
  CONSTRAINT arena_groups_vip_family_shape CHECK (
    (group_type = 'vip' AND vip_family_key IS NOT NULL) OR
    (group_type <> 'vip' AND vip_family_key IS NULL)
  ),
  CONSTRAINT arena_groups_vip_family_valid CHECK (
    vip_family_key IS NULL OR
    vip_family_key REGEXP '^[a-z0-9][a-z0-9._:-]{0,63}$'
  ),
  CONSTRAINT arena_groups_badge_color_valid CHECK (
    badge_color REGEXP '^#[0-9A-Fa-f]{6}$'
  ),
  CONSTRAINT arena_groups_badge_soft_color_valid CHECK (
    badge_soft_color REGEXP '^#[0-9A-Fa-f]{6}$'
  ),
  CONSTRAINT arena_groups_definition_valid CHECK (JSON_VALID(definition)),
  CONSTRAINT arena_groups_permissions_valid CHECK (
    JSON_VALID(baseline_permissions)
  ),
  CONSTRAINT arena_groups_capabilities_valid CHECK (
    JSON_VALID(capability_keys)
  ),
  CONSTRAINT arena_groups_version_positive CHECK (row_version >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS arena_group_scopes (
  group_id BIGINT UNSIGNED NOT NULL,
  scope_id BIGINT UNSIGNED NOT NULL,
  definition_override JSON NULL,
  rank_weight_override INT NULL,
  immunity_override INT UNSIGNED NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_by_actor VARCHAR(64) NOT NULL,
  updated_by_actor VARCHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (group_id, scope_id),
  KEY arena_group_scopes_scope (scope_id, enabled, group_id),
  CONSTRAINT arena_group_scopes_group_fk FOREIGN KEY (group_id)
    REFERENCES arena_groups (id) ON DELETE RESTRICT,
  CONSTRAINT arena_group_scopes_scope_fk FOREIGN KEY (scope_id)
    REFERENCES arena_scopes (id) ON DELETE RESTRICT,
  CONSTRAINT arena_group_scopes_definition_valid CHECK (
    definition_override IS NULL OR JSON_VALID(definition_override)
  ),
  CONSTRAINT arena_group_scopes_version_positive CHECK (row_version >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Every command is inserted before its effects and selected FOR UPDATE by the
-- writer. The issuer/request key and request hash make retries deterministic;
-- the explicit reservation key prevents one item being redeemed under two
-- non-rejected command UUIDs even if a caller changes its idempotency key.
CREATE TABLE IF NOT EXISTS arena_membership_commands (
  command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  issuer ENUM('portal', 'staff', 'game', 'migration', 'system') NOT NULL,
  issuer_request_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  command_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  actor_steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NULL,
  target_steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  target_group_id BIGINT UNSIGNED NULL,
  target_scope_id BIGINT UNSIGNED NULL,
  vip_family_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  source_inventory_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  request_payload JSON NOT NULL,
  rate_snapshot JSON NULL,
  rate_snapshot_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  rate_snapshot_expires_at DATETIME(6) NULL,
  status ENUM(
    'received',
    'processing',
    'applied',
    'rejected',
    'manual_review'
  ) NOT NULL DEFAULT 'received',
  -- The writer copies source_inventory_item_id here on insert and clears it in
  -- the same statement that records a durable rejection. This explicit key is
  -- used instead of an ENUM-dependent generated column, which MariaDB 10.5
  -- rejects. Every other state keeps the reservation unique, including
  -- manual_review and applied.
  reserved_inventory_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  error_message VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  applied_at DATETIME(6) NULL,
  PRIMARY KEY (command_uuid),
  UNIQUE KEY arena_membership_commands_request
    (issuer, issuer_request_key),
  UNIQUE KEY arena_membership_commands_reserved_item
    (reserved_inventory_item_id),
  KEY arena_membership_commands_target
    (target_steam_id, status, created_at, command_uuid),
  KEY arena_membership_commands_recovery
    (status, updated_at, command_uuid),
  KEY arena_membership_commands_group_scope
    (target_group_id, target_scope_id, status),
  CONSTRAINT arena_membership_commands_group_scope_fk FOREIGN KEY
    (target_group_id, target_scope_id)
    REFERENCES arena_group_scopes (group_id, scope_id) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_commands_uuid_valid CHECK (
    command_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_membership_commands_hash_valid CHECK (
    request_hash REGEXP '^[0-9a-f]{64}$'
  ),
  CONSTRAINT arena_membership_commands_type_valid CHECK (
    command_type REGEXP '^[a-z][a-z0-9._:-]{0,63}$'
  ),
  CONSTRAINT arena_membership_commands_payload_valid CHECK (
    JSON_VALID(request_payload)
  ),
  CONSTRAINT arena_membership_commands_rate_shape CHECK (
    (
      rate_snapshot IS NULL AND
      rate_snapshot_hash IS NULL AND
      rate_snapshot_expires_at IS NULL
    ) OR
    (
      rate_snapshot IS NOT NULL AND
      JSON_VALID(rate_snapshot) AND
      rate_snapshot_hash REGEXP '^[0-9a-f]{64}$' AND
      rate_snapshot_expires_at IS NOT NULL
    )
  ),
  CONSTRAINT arena_membership_commands_reservation_shape CHECK (
    reserved_inventory_item_id IS NULL OR
    reserved_inventory_item_id = source_inventory_item_id
  ),
  CONSTRAINT arena_membership_commands_rejected_releases_item CHECK (
    status <> 'rejected' OR reserved_inventory_item_id IS NULL
  )
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Rolling-upgrade hardening for preview installations. CREATE TABLE IF NOT
-- EXISTS cannot add the explicit reservation column to an existing table.
-- Do not attempt an in-place generated-column conversion here: MariaDB 10.5
-- rejects the old ENUM-dependent expression, and conversion behavior differs
-- across engines. Fail before changing data so an operator can explicitly
-- convert a MySQL preview column to an ordinary nullable CHAR(36).
SET @arena_commands_reservation_is_generated = (
  SELECT COUNT(*)
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'arena_membership_commands'
    AND COLUMN_NAME = 'reserved_inventory_item_id'
    AND (
      EXTRA LIKE '%GENERATED%' OR
      COALESCE(GENERATION_EXPRESSION, '') <> ''
    )
);
SET @arena_commands_generated_guard_sql = IF(
  @arena_commands_reservation_is_generated = 0,
  'SELECT 1',
  'SELECT 1 FROM `arena_upgrade_blocked__reserved_inventory_item_id_is_generated__convert_to_ordinary_char36`'
);
PREPARE arena_commands_generated_guard_statement
  FROM @arena_commands_generated_guard_sql;
EXECUTE arena_commands_generated_guard_statement;
DEALLOCATE PREPARE arena_commands_generated_guard_statement;

SET @arena_commands_reservation_column_exists = (
  SELECT COUNT(*)
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'arena_membership_commands'
    AND COLUMN_NAME = 'reserved_inventory_item_id'
);
SET @arena_commands_reservation_column_sql = IF(
  @arena_commands_reservation_column_exists > 0,
  'SELECT 1',
  'ALTER TABLE arena_membership_commands ADD COLUMN reserved_inventory_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL AFTER status'
);
PREPARE arena_commands_reservation_column_statement
  FROM @arena_commands_reservation_column_sql;
EXECUTE arena_commands_reservation_column_statement;
DEALLOCATE PREPARE arena_commands_reservation_column_statement;

-- Backfill uses the immutable source item identity. Multiple rejected attempts
-- intentionally collapse to NULL; two non-rejected commands for one item are
-- a conflict and must stop the migration before a unique index is attempted.
SET @arena_commands_duplicate_reservations = (
  SELECT COUNT(*)
  FROM (
    SELECT source_inventory_item_id
    FROM arena_membership_commands
    WHERE source_inventory_item_id IS NOT NULL
      AND status <> 'rejected'
    GROUP BY source_inventory_item_id
    HAVING COUNT(*) > 1
  ) AS duplicate_reservations
);
SET @arena_commands_duplicate_guard_sql = IF(
  @arena_commands_duplicate_reservations = 0,
  'SELECT 1',
  'SELECT 1 FROM `arena_upgrade_blocked__duplicate_active_inventory_reservations`'
);
PREPARE arena_commands_duplicate_guard_statement
  FROM @arena_commands_duplicate_guard_sql;
EXECUTE arena_commands_duplicate_guard_statement;
DEALLOCATE PREPARE arena_commands_duplicate_guard_statement;

UPDATE arena_membership_commands
SET reserved_inventory_item_id = CASE
  WHEN status = 'rejected' THEN NULL
  ELSE source_inventory_item_id
END
WHERE NOT (
  reserved_inventory_item_id <=> CASE
    WHEN status = 'rejected' THEN NULL
    ELSE source_inventory_item_id
  END
);

SET @arena_commands_reservation_index_exists = (
  SELECT COUNT(DISTINCT INDEX_NAME)
  FROM information_schema.STATISTICS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'arena_membership_commands'
    AND INDEX_NAME = 'arena_membership_commands_reserved_item'
);
SET @arena_commands_reservation_index_valid = (
  SELECT COUNT(*)
  FROM (
    SELECT INDEX_NAME
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'arena_membership_commands'
      AND INDEX_NAME = 'arena_membership_commands_reserved_item'
    GROUP BY INDEX_NAME
    HAVING MAX(NON_UNIQUE) = 0
      AND COUNT(*) = 1
      AND MAX(COLUMN_NAME) = 'reserved_inventory_item_id'
      AND MAX(SUB_PART IS NULL) = 1
  ) AS valid_reservation_index
);
SET @arena_commands_reservation_index_guard_sql = IF(
  @arena_commands_reservation_index_exists = 0 OR
    @arena_commands_reservation_index_valid = 1,
  'SELECT 1',
  'SELECT 1 FROM `arena_upgrade_blocked__reserved_inventory_item_index_has_wrong_shape`'
);
PREPARE arena_commands_reservation_index_guard_statement
  FROM @arena_commands_reservation_index_guard_sql;
EXECUTE arena_commands_reservation_index_guard_statement;
DEALLOCATE PREPARE arena_commands_reservation_index_guard_statement;

SET @arena_commands_reservation_index_sql = IF(
  @arena_commands_reservation_index_exists > 0,
  'SELECT 1',
  'ALTER TABLE arena_membership_commands ADD UNIQUE INDEX arena_membership_commands_reserved_item (reserved_inventory_item_id)'
);
PREPARE arena_commands_reservation_index_statement
  FROM @arena_commands_reservation_index_sql;
EXECUTE arena_commands_reservation_index_statement;
DEALLOCATE PREPARE arena_commands_reservation_index_statement;

-- Preview DDL used a global UNIQUE(source_inventory_item_id), which prevents a
-- safely rejected item from being attempted again. Remove only exact, single-
-- column unique indexes on that legacy source field after the reservation
-- index is known to be present.
SET @arena_commands_legacy_unique_drops = (
  SELECT GROUP_CONCAT(
    CONCAT('DROP INDEX `', REPLACE(INDEX_NAME, '`', '``'), '`')
    ORDER BY INDEX_NAME SEPARATOR ', '
  )
  FROM (
    SELECT INDEX_NAME
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'arena_membership_commands'
      AND INDEX_NAME <> 'PRIMARY'
    GROUP BY INDEX_NAME
    HAVING MAX(NON_UNIQUE) = 0
      AND COUNT(*) = 1
      AND MAX(COLUMN_NAME) = 'source_inventory_item_id'
  ) AS legacy_unique_indexes
);
SET @arena_commands_legacy_unique_sql = IF(
  @arena_commands_legacy_unique_drops IS NULL,
  'SELECT 1',
  CONCAT(
    'ALTER TABLE arena_membership_commands ',
    @arena_commands_legacy_unique_drops
  )
);
PREPARE arena_commands_legacy_unique_statement
  FROM @arena_commands_legacy_unique_sql;
EXECUTE arena_commands_legacy_unique_statement;
DEALLOCATE PREPARE arena_commands_legacy_unique_statement;

CREATE TABLE IF NOT EXISTS arena_group_memberships (
  membership_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  group_id BIGINT UNSIGNED NOT NULL,
  scope_id BIGINT UNSIGNED NOT NULL,
  steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  starts_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  expires_at DATETIME(6) NULL,
  status ENUM('active', 'revoked', 'superseded', 'conflict')
    NOT NULL DEFAULT 'active',
  provenance_type ENUM(
    'staff',
    'inventory',
    'game',
    'legacy_portal',
    'legacy_vip_users',
    'legacy_admins',
    'migration',
    'system'
  ) NOT NULL,
  provenance_reference VARCHAR(191) NULL,
  source_inventory_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  origin_command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  granted_by_actor VARCHAR(64) NOT NULL,
  grant_reason VARCHAR(180) NULL,
  revoked_at DATETIME(6) NULL,
  revoked_by_actor VARCHAR(64) NULL,
  revoke_reason VARCHAR(180) NULL,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (membership_uuid),
  UNIQUE KEY arena_group_memberships_one_row
    (group_id, scope_id, steam_id),
  UNIQUE KEY arena_group_memberships_inventory_item
    (source_inventory_item_id),
  UNIQUE KEY arena_group_memberships_subscription_ref
    (membership_uuid, group_id, scope_id, steam_id),
  KEY arena_group_memberships_player
    (steam_id, scope_id, status, expires_at, group_id),
  KEY arena_group_memberships_group
    (group_id, scope_id, status, expires_at, steam_id),
  KEY arena_group_memberships_origin (origin_command_uuid),
  CONSTRAINT arena_group_memberships_group_scope_fk FOREIGN KEY
    (group_id, scope_id)
    REFERENCES arena_group_scopes (group_id, scope_id) ON DELETE RESTRICT,
  CONSTRAINT arena_group_memberships_origin_fk FOREIGN KEY
    (origin_command_uuid)
    REFERENCES arena_membership_commands (command_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_group_memberships_uuid_valid CHECK (
    membership_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_group_memberships_steam_valid CHECK (
    steam_id REGEXP '^7656119[0-9]{10}$'
  ),
  CONSTRAINT arena_group_memberships_date_range CHECK (
    expires_at IS NULL OR expires_at > starts_at
  ),
  CONSTRAINT arena_group_memberships_version_positive CHECK (row_version >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- This row is the lock and the complete current state for a VIP family. It
-- replaces both cross-tier vip_users stacking and the portal suppression
-- ledger. A player may have one VIP subscription per explicit scope/family.
CREATE TABLE IF NOT EXISTS arena_vip_subscriptions (
  steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope_id BIGINT UNSIGNED NOT NULL,
  vip_family_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci
    NOT NULL,
  group_id BIGINT UNSIGNED NULL,
  group_type ENUM('admin', 'vip', 'custom') NOT NULL DEFAULT 'vip',
  membership_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  status ENUM('active', 'ended', 'conflict') NOT NULL DEFAULT 'active',
  starts_at DATETIME(6) NULL,
  expires_at DATETIME(6) NULL,
  legacy_suppressed_until DATETIME(6) NULL,
  legacy_suppressed_permanently BOOLEAN NOT NULL DEFAULT FALSE,
  last_command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  row_version BIGINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
    ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (steam_id, scope_id, vip_family_key),
  UNIQUE KEY arena_vip_subscriptions_membership (membership_uuid),
  KEY arena_vip_subscriptions_group
    (group_id, scope_id, status, expires_at, steam_id),
  KEY arena_vip_subscriptions_group_family
    (group_id, group_type, vip_family_key),
  KEY arena_vip_subscriptions_membership_ref
    (membership_uuid, group_id, scope_id, steam_id),
  KEY arena_vip_subscriptions_command (last_command_uuid),
  CONSTRAINT arena_vip_subscriptions_scope_fk FOREIGN KEY (scope_id)
    REFERENCES arena_scopes (id) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_subscriptions_group_scope_fk FOREIGN KEY
    (group_id, scope_id)
    REFERENCES arena_group_scopes (group_id, scope_id) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_subscriptions_group_family_fk FOREIGN KEY
    (group_id, group_type, vip_family_key)
    REFERENCES arena_groups (id, group_type, vip_family_key)
    ON DELETE RESTRICT,
  CONSTRAINT arena_vip_subscriptions_membership_fk FOREIGN KEY
    (membership_uuid, group_id, scope_id, steam_id)
    REFERENCES arena_group_memberships
      (membership_uuid, group_id, scope_id, steam_id)
    ON DELETE RESTRICT,
  CONSTRAINT arena_vip_subscriptions_command_fk FOREIGN KEY
    (last_command_uuid)
    REFERENCES arena_membership_commands (command_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_subscriptions_steam_valid CHECK (
    steam_id REGEXP '^7656119[0-9]{10}$'
  ),
  CONSTRAINT arena_vip_subscriptions_family_valid CHECK (
    vip_family_key REGEXP '^[a-z0-9][a-z0-9._:-]{0,63}$'
  ),
  CONSTRAINT arena_vip_subscriptions_group_type_valid CHECK (
    group_type = 'vip'
  ),
  CONSTRAINT arena_vip_subscriptions_active_shape CHECK (
    status <> 'active' OR
    (group_id IS NOT NULL AND membership_uuid IS NOT NULL AND starts_at IS NOT NULL)
  ),
  CONSTRAINT arena_vip_subscriptions_date_range CHECK (
    expires_at IS NULL OR (starts_at IS NOT NULL AND expires_at > starts_at)
  ),
  CONSTRAINT arena_vip_subscriptions_suppression_shape CHECK (
    legacy_suppressed_permanently = FALSE OR
    legacy_suppressed_until IS NULL
  ),
  CONSTRAINT arena_vip_subscriptions_active_suppression CHECK (
    status <> 'active' OR
    legacy_suppressed_permanently = TRUE OR
    (
      expires_at IS NOT NULL AND
      legacy_suppressed_until IS NOT NULL AND
      legacy_suppressed_until >= expires_at
    )
  ),
  CONSTRAINT arena_vip_subscriptions_version_positive CHECK (row_version >= 1)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS arena_vip_subscription_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  transition_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  scope_id BIGINT UNSIGNED NOT NULL,
  vip_family_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci
    NOT NULL,
  action VARCHAR(48) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  from_group_id BIGINT UNSIGNED NULL,
  to_group_id BIGINT UNSIGNED NULL,
  membership_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  source_inventory_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  actor_steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NULL,
  before_expires_at DATETIME(6) NULL,
  after_expires_at DATETIME(6) NULL,
  item_duration_seconds BIGINT UNSIGNED NULL,
  converted_duration_seconds BIGINT UNSIGNED NULL,
  conversion_source_seconds BIGINT UNSIGNED NULL,
  time_deducted_seconds BIGINT UNSIGNED NULL,
  rate_snapshot_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  metadata JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY arena_vip_history_transition_unique (transition_uuid),
  KEY arena_vip_history_player
    (steam_id, scope_id, vip_family_key, created_at, id),
  KEY arena_vip_history_command (command_uuid),
  KEY arena_vip_history_item (source_inventory_item_id),
  CONSTRAINT arena_vip_history_scope_fk FOREIGN KEY (scope_id)
    REFERENCES arena_scopes (id) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_history_from_group_fk FOREIGN KEY (from_group_id)
    REFERENCES arena_groups (id) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_history_to_group_fk FOREIGN KEY (to_group_id)
    REFERENCES arena_groups (id) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_history_membership_fk FOREIGN KEY (membership_uuid)
    REFERENCES arena_group_memberships (membership_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_history_command_fk FOREIGN KEY (command_uuid)
    REFERENCES arena_membership_commands (command_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_vip_history_transition_uuid_valid CHECK (
    transition_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_vip_history_action_valid CHECK (
    action REGEXP '^[a-z][a-z0-9._:-]{0,47}$'
  ),
  CONSTRAINT arena_vip_history_hash_valid CHECK (
    rate_snapshot_hash IS NULL OR rate_snapshot_hash REGEXP '^[0-9a-f]{64}$'
  ),
  CONSTRAINT arena_vip_history_metadata_valid CHECK (JSON_VALID(metadata))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS arena_membership_command_receipts (
  command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  outcome ENUM('applied', 'rejected') NOT NULL,
  membership_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  subscription_row_version BIGINT UNSIGNED NULL,
  result_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  result JSON NOT NULL,
  recorded_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (command_uuid),
  KEY arena_membership_receipts_membership (membership_uuid),
  CONSTRAINT arena_membership_receipts_command_fk FOREIGN KEY (command_uuid)
    REFERENCES arena_membership_commands (command_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_receipts_membership_fk FOREIGN KEY
    (membership_uuid)
    REFERENCES arena_group_memberships (membership_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_receipts_hash_valid CHECK (
    result_hash REGEXP '^[0-9a-f]{64}$'
  ),
  CONSTRAINT arena_membership_receipts_result_valid CHECK (JSON_VALID(result))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- The portal acknowledges these rows only after its own inventory transaction
-- commits. Membership state and the event are written in the same arena
-- transaction, so a portal outage cannot lose the work that remains to be
-- reflected in inventory rewards, badges, or notifications.
CREATE TABLE IF NOT EXISTS arena_membership_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  deduplication_key VARCHAR(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  event_type VARCHAR(80) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  aggregate_type VARCHAR(48) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  aggregate_key VARCHAR(191) NOT NULL,
  command_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  membership_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
  steam_id VARCHAR(17) CHARACTER SET ascii COLLATE ascii_bin NULL,
  group_id BIGINT UNSIGNED NULL,
  scope_id BIGINT UNSIGNED NULL,
  payload JSON NOT NULL,
  status ENUM('pending', 'processing', 'published', 'failed')
    NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  locked_by VARCHAR(96) NULL,
  locked_at DATETIME(6) NULL,
  published_at DATETIME(6) NULL,
  last_error VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY arena_membership_outbox_event_unique (event_uuid),
  UNIQUE KEY arena_membership_outbox_dedupe_unique (deduplication_key),
  KEY arena_membership_outbox_delivery
    (status, available_at, id),
  KEY arena_membership_outbox_processing
    (status, locked_at, id),
  KEY arena_membership_outbox_player
    (steam_id, created_at, id),
  KEY arena_membership_outbox_group_scope
    (group_id, scope_id, id),
  CONSTRAINT arena_membership_outbox_command_fk FOREIGN KEY (command_uuid)
    REFERENCES arena_membership_commands (command_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_outbox_membership_fk FOREIGN KEY
    (membership_uuid)
    REFERENCES arena_group_memberships (membership_uuid) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_outbox_group_scope_fk FOREIGN KEY
    (group_id, scope_id)
    REFERENCES arena_group_scopes (group_id, scope_id) ON DELETE RESTRICT,
  CONSTRAINT arena_membership_outbox_event_uuid_valid CHECK (
    event_uuid REGEXP '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  ),
  CONSTRAINT arena_membership_outbox_event_type_valid CHECK (
    event_type REGEXP '^[a-z][a-z0-9._:-]{0,79}$'
  ),
  CONSTRAINT arena_membership_outbox_aggregate_type_valid CHECK (
    aggregate_type REGEXP '^[a-z][a-z0-9._:-]{0,47}$'
  ),
  CONSTRAINT arena_membership_outbox_payload_valid CHECK (JSON_VALID(payload))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
