export type Tokens = string;
export type PanelRequest<A> = { actorSteamId: string; operationId: string; arguments: A };
export type PanelError = { code: string; message: string; retryable: boolean; retryAfterMs?: number };
export type PanelResponse<T> = { data: T | null; operationId: string | null; error?: PanelError };
export type Page<T> = { items: T[]; total: number; page: number; pageSize: number };
export type Wallet = { balance: Tokens; lifetimeEarned: Tokens; lifetimeSpent: Tokens };
export type Slot = { slotType: 'weapon'; team: 'T'|'CT'; definitionIndex: number } | { slotType: 'knife'|'glove'|'agent'; team: 'T'|'CT' } | { slotType: 'music_kit' };
export type Item = {
  id:string; catalogueId:number|null; itemType:string; displayName:string; imageUrl:string|null;
  rarityRank:number; definitionIndex:number|null; paintkit:number|null; floatValue:number|null; seed:number|null;
  stattrak:boolean; stattrakCount:number; nametag:string|null; state:string; saleLocked:boolean; tradable:boolean;
  equippedSlotKeys:string[]; marketPriceTokens:Tokens|null; sellbackPayoutTokens:Tokens|null;
  capabilities:{equip:boolean;equipTargets?:('T'|'CT'|'both'|'global')[];rename:boolean;stickerSlots:number;charm:boolean;open:boolean;vip:boolean;theme:boolean};
};
export type TradePreview = Pick<Item,'id'|'catalogueId'|'itemType'|'displayName'|'imageUrl'|'rarityRank'|'definitionIndex'|'paintkit'|'floatValue'|'seed'|'stattrak'|'stattrakCount'|'nametag'>;
export type ItemDetail = Item & {stickers:{slot:number;stickerItemId:string;displayName:string|null}[];charm:{definitionIndex:number;displayName:string|null}|null;minFloat:number|null;maxFloat:number|null};
export type Product = {catalogueId:number;itemType:string;displayName:string;imageUrl:string|null;rarityRank:number;definitionIndex:number|null;paintkit:number|null;minFloat:number|null;maxFloat:number|null;priceTokens:Tokens|null;supportsStattrak:boolean;maximumQuantity:number};
export type Quote = {catalogueId:number;quantity:number;unitPriceTokens:Tokens;totalPriceTokens:Tokens;floatValue:number|null;seed:number|null;stattrak:boolean;quotedAt:string};
export type Opening = {openingId:number;crateItemId:string;rewardItemId:string;rewardCatalogueId:number;rewardLootEntryId:number;rewardRarityRank:number;reward:TradePreview;globalAnnouncementQueued:boolean};
export type Openings = {openings:Opening[];crateItemIds:string[]};
export type Loadout = {slots:{slot:Slot;slotKey:string;itemId:string|null}[]};
export type VipQuote = {itemId:string;eligible:boolean;reasonCode:string|null;activationKind:'activated'|'extended'|'lower-tier-converted'|'upgraded'|'made-permanent'|'permanent-upgrade'|null;groupName:string|null;convertedDurationSeconds:number;timeDeductedSeconds:number;expiresAt:string|null;quotedAt:string;advisory:true};
export type VipActivation = {itemId:string;catalogueId:number;itemGroupId:number;itemGroupName:string;groupId:number;groupKey:string;groupName:string;sourceType:string;durationMinutes:number;activationKind:NonNullable<VipQuote['activationKind']>;previousGroupName:string|null;convertedDurationSeconds:number;conversionSourceSeconds:number;timeDeductedSeconds:number;expiresAt:string|null};
export type TradeStatus = 'pending'|'accepted'|'rejected'|'cancelled'|'expired';
export type Trade = {id:string;creatorSteamId:string;counterpartySteamId:string;direction:'incoming'|'outgoing';status:TradeStatus;offered:{steamId:string;tokens:Tokens;items:TradePreview[]};requested:{steamId:string;tokens:Tokens;items:TradePreview[]};expiresAt:string|null;updatedAt:string};
export type OperationStatus = {status:'pending'|'completed'|'failed'|'expired';result:unknown|null;error:PanelError|null};
export type Filters = {query?:string;itemTypes?:string[];rarityRanks?:number[];sort?:'newest'|'name'|'rarity'|'float'|'price';category?:'rifles'|'snipers'|'pistols'|'smgs'|'shotguns'|'lmgs'|'other';definitionIndex?:number;page?:number;pageSize?:12|24|48};
type Selection = {catalogueId:number;quantity:number;floatValue?:number;seed?:number;stattrak:boolean};
type ItemId = {itemId:string};
type Paging = {page?:number;pageSize?:12|24|48};
export type PanelArguments = {
  'wallet.read': Record<string, never>;
  'inventory.read': Filters & {hideEquipped?:boolean}; 'inventory.detail':ItemId;
  'inventory.protect':{itemIds:string[];saleLocked:boolean}; 'inventory.sell':{itemIds:string[]};
  'cases.read':Filters; 'cases.drops':Paging & {catalogueId:number}; 'cases.open':{crateItemId:string};
  'cases.open-bulk':{crateItemIds:string[]}; 'cases.reconcile':{crateItemIds:string[]};
  'market.read':Filters & {minFloat?:number;maxFloat?:number}; 'market.detail':{catalogueId:number};
  'market.quote':Selection; 'market.purchase':Selection & {expectedUnitPriceTokens:Tokens};
  'loadout.read':Record<string,never>; 'loadout.equip':ItemId & {slots:Slot[]}; 'loadout.clear':{slots:Slot[]};
  'customize.rename':ItemId & {nametag:string;nametagItemId?:string};
  'customize.sticker':{weaponItemId:string;stickerItemId:string;slot:number}; 'customize.charm':{weaponItemId:string;charmItemId:string};
  'benefits.vip-quote':ItemId; 'benefits.vip-activate':ItemId; 'benefits.theme-equip':ItemId; 'benefits.redeem':{code:string};
  'trades.partners':{query:string;onlineSteamIds:string[]};
  'trades.inventory':Paging & {partnerSteamId:string;query?:string;onlineSteamIds:string[]};
  'trades.read':Paging & {status?:TradeStatus[]}; 'trades.detail':{tradeId:string};
  'trades.create':{counterpartySteamId:string;offeredItemIds:string[];requestedItemIds:string[];offeredTokens:Tokens;requestedTokens:Tokens;onlineSteamIds:string[]};
  'trades.respond':{tradeId:string;decision:'accept'|'decline'}; 'trades.cancel':{tradeId:string}; 'operations.status':{targetOperationId:string};
};
export type PanelOperation = keyof PanelArguments;
export const PANEL_OPERATIONS: readonly PanelOperation[] = ['wallet.read','inventory.read','inventory.detail','inventory.protect','inventory.sell','cases.read','cases.drops','cases.open','cases.open-bulk','cases.reconcile','market.read','market.detail','market.quote','market.purchase','loadout.read','loadout.equip','loadout.clear','customize.rename','customize.sticker','customize.charm','benefits.vip-quote','benefits.vip-activate','benefits.theme-equip','benefits.redeem','trades.partners','trades.inventory','trades.read','trades.detail','trades.create','trades.respond','trades.cancel','operations.status'];
export const MUTATION_OPERATIONS = new Set<PanelOperation>(['inventory.protect','inventory.sell','cases.open','cases.open-bulk','market.purchase','loadout.equip','loadout.clear','customize.rename','customize.sticker','customize.charm','benefits.vip-activate','benefits.theme-equip','benefits.redeem','trades.create','trades.respond','trades.cancel']);
export type PanelData = {
  'wallet.read':Wallet;'inventory.read':Page<Item>;'inventory.detail':ItemDetail;'inventory.protect':{itemIds:string[];saleLocked:boolean};'inventory.sell':{itemIds:string[];skippedItemIds:string[];payoutTokens:Tokens;wallet:Wallet};
  'cases.read':Page<Item>;'cases.drops':Page<{lootEntryId:number;product:Product;weight:number;minFloat:number|null;maxFloat:number|null;stattrakChanceBps:number}> & {totalWeight:number};'cases.open':Openings;'cases.open-bulk':Openings;'cases.reconcile':Openings & {missingCrateItemIds:string[]};
  'market.read':Page<Product>;'market.detail':Product;'market.quote':Quote;'market.purchase':{itemIds:string[];quantity:number;unitPriceTokens:Tokens;totalPriceTokens:Tokens;wallet:Wallet};
  'loadout.read':Loadout;'loadout.equip':{itemId:string;loadout:Loadout};'loadout.clear':{loadout:Loadout};
  'customize.rename':{itemId:string;nametag:string;priceTokens:Tokens;wallet:Wallet};'customize.sticker':{weaponItemId:string;stickerItemId:string;slot:number};'customize.charm':{weaponItemId:string;charmItemId:string;charmDefinitionIndex:number};
  'benefits.vip-quote':VipQuote;'benefits.vip-activate':VipActivation;'benefits.theme-equip':{itemId:string;catalogueId:number;themeId:number;themeKey:string;displayName:string};'benefits.redeem':{codeId:number;displayName:string;tokensAwarded:Tokens;itemIds:string[];itemNames:string[];wallet:Wallet};
  'trades.partners':{players:{steamId:string;displayName:string;inventoryVisibility:string}[]};'trades.inventory':{visibility:string;items:TradePreview[];total?:number;page:number;pageSize:number};'trades.read':Page<Trade>;'trades.detail':Trade;'trades.create':{tradeId:string;status:'pending';expiresAt:string};'trades.respond':{tradeId:string;status:TradeStatus;reason?:string};'trades.cancel':{tradeId:string;status:'cancelled'|'expired'};'operations.status':OperationStatus;
};
export type PanelPrincipal = {serverId:string;keyId:string;actorSteamId:string;allowedOperations:ReadonlySet<PanelOperation>};
